#
# Minimap configuration file
# Lines starting with "#" (like this one) are comments

# PAL 2 Brown Green
background 0 0 0
none 80 100 70
sinkhole 90 70 50
woods 100 180 100
heavywoods 70 150 70
ultraheavywoods 40 120 40
rough 90 110 80
rubble 110 120 110
water 0 130 130
pavement 90 90 80
road 60 60 50
fire 255 120 0
smoke 100 100 90
smokeandfire 200 80 0
swamp 60 100 60
building 100 100 90
bridge 80 80 70

# unit size: defines the size of the triangle for unit representation
unitsize 6
