#
# Minimap configuration file
# Lines starting with "#" (like this one) are comments

# Pal 8 GBC
background 15 56 15
none 48 98 48
sinkhole 63 127 63
woods 79 159 79
heavywoods 63 127 63
ultraheavywoods 15 56 15
rough 48 98 48
rubble 79 159 79
water 48 98 48
pavement 63 127 63
road 48 98 48
fire 255 102 0
smoke 63 127 63
smokeandfire 79 159 79
swamp 48 98 48
building 63 127 63
bridge 48 98 48

# unit size: defines the size of the triangle for unit representation
unitsize 6
