#
# Minimap configuration file
# Lines starting with "#" (like this one) are comments

#pal 12 Red Amaranth
background 15 15 15
none 229 43 80
sinkhole 180 34 65
woods 110 20 40
heavywoods 85 15 30
ultraheavywoods 50 10 20
rough 140 30 50
rubble 200 50 70
water 20 20 20
pavement 50 50 50
road 30 30 30
fire 255 69 0
smoke 50 50 50
smokeandfire 180 30 50
swamp 110 20 40
building 100 100 100
bridge 40 40 40

# unit size: defines the size of the triangle for unit representation
unitsize 6
