#
# Minimap configuration file
# Lines starting with "#" (like this one) are comments

# Pal 9 Battlezone
background 2 56 33
none 196 245 186
sinkhole 33 207 33
woods 2 56 33
heavywoods 33 207 33
ultraheavywoods 2 56 33
rough 196 245 186
rubble 33 207 33
water 1 37 51
pavement 196 245 186
road 33 207 33
fire 236 62 11
smoke 33 207 33
smokeandfire 236 62 11
swamp 33 207 33
building 196 245 186
bridge 1 37 51

# unit size: defines the size of the triangle for unit representation
unitsize 6
