# CodeCov.io Configuration
# https://docs.codecov.io/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true

    patch:
      default:
        informational: true

fixes:
  - "megamek/::"

github_checks:
  annotations: false
