/*
 * Copyright (C) 2024-2025 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MegaMek.
 *
 * MegaMek is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MegaMek is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MegaMek was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package megamek.client.ui.dialogs.advancedsearch;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import megamek.client.ui.Messages;

class TransportsSearchTab extends JPanel {

    final JButton btnTransportsClear = new JButton(Messages.getString("MekSelectorDialog.ClearTab"));
    final JLabel lblTroopSpace = new JLabel(Messages.getString("MekSelectorDialog.Search.TroopSpace"));
    final JTextField tStartTroopSpace = new JTextField(4);
    final JTextField tEndTroopSpace = new JTextField(4);
    final JLabel lblASFBays = new JLabel(Messages.getString("MekSelectorDialog.Search.ASFBays"));
    final JTextField tStartASFBays = new JTextField(4);
    final JTextField tEndASFBays = new JTextField(4);
    final JLabel lblASFDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartASFDoors = new JTextField(4);
    final JTextField tEndASFDoors = new JTextField(4);
    final JLabel lblASFUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartASFUnits = new JTextField(4);
    final JTextField tEndASFUnits = new JTextField(4);
    final JLabel lblSmallCraftBays = new JLabel(Messages.getString("MekSelectorDialog.Search.SmallCraftBays"));
    final JTextField tStartSmallCraftBays = new JTextField(4);
    final JTextField tEndSmallCraftBays = new JTextField(4);
    final JLabel lblSmallCraftDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartSmallCraftDoors = new JTextField(4);
    final JTextField tEndSmallCraftDoors = new JTextField(4);
    final JLabel lblSmallCraftUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartSmallCraftUnits = new JTextField(4);
    final JTextField tEndSmallCraftUnits = new JTextField(4);
    final JLabel lblMekBays = new JLabel(Messages.getString("MekSelectorDialog.Search.MekBays"));
    final JTextField tStartMekBays = new JTextField(4);
    final JTextField tEndMekBays = new JTextField(4);
    final JLabel lblMekDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartMekDoors = new JTextField(4);
    final JTextField tEndMekDoors = new JTextField(4);
    final JLabel lblMekUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartMekUnits = new JTextField(4);
    final JTextField tEndMekUnits = new JTextField(4);
    final JLabel lblHeavyVehicleBays = new JLabel(Messages.getString("MekSelectorDialog.Search.HeavyVehicleBays"));
    final JTextField tStartHeavyVehicleBays = new JTextField(4);
    final JTextField tEndHeavyVehicleBays = new JTextField(4);
    final JLabel lblHeavyVehicleDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartHeavyVehicleDoors = new JTextField(4);
    final JTextField tEndHeavyVehicleDoors = new JTextField(4);
    final JLabel lblHeavyVehicleUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartHeavyVehicleUnits = new JTextField(4);
    final JTextField tEndHeavyVehicleUnits = new JTextField(4);
    final JLabel lblLightVehicleBays = new JLabel(Messages.getString("MekSelectorDialog.Search.LightVehicleBays"));
    final JTextField tStartLightVehicleBays = new JTextField(4);
    final JTextField tEndLightVehicleBays = new JTextField(4);
    final JLabel lblLightVehicleDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartLightVehicleDoors = new JTextField(4);
    final JTextField tEndLightVehicleDoors = new JTextField(4);
    final JLabel lblLightVehicleUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartLightVehicleUnits = new JTextField(4);
    final JTextField tEndLightVehicleUnits = new JTextField(4);
    final JLabel lblProtomekBays = new JLabel(Messages.getString("MekSelectorDialog.Search.ProtomekBays"));
    final JTextField tStartProtomekBays = new JTextField(4);
    final JTextField tEndProtomekBays = new JTextField(4);
    final JLabel lblProtomekDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartProtomekDoors = new JTextField(4);
    final JTextField tEndProtomekDoors = new JTextField(4);
    final JLabel lblProtomekUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartProtomekUnits = new JTextField(4);
    final JTextField tEndProtomekUnits = new JTextField(4);
    final JLabel lblBattleArmorBays = new JLabel(Messages.getString("MekSelectorDialog.Search.BattleArmorBays"));
    final JTextField tStartBattleArmorBays = new JTextField(4);
    final JTextField tEndBattleArmorBays = new JTextField(4);
    final JLabel lblBattleArmorDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartBattleArmorDoors = new JTextField(4);
    final JTextField tEndBattleArmorDoors = new JTextField(4);
    final JLabel lblBattleArmorUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartBattleArmorUnits = new JTextField(4);
    final JTextField tEndBattleArmorUnits = new JTextField(4);
    final JLabel lblInfantryBays = new JLabel(Messages.getString("MekSelectorDialog.Search.InfantryBays"));
    final JTextField tStartInfantryBays = new JTextField(4);
    final JTextField tEndInfantryBays = new JTextField(4);
    final JLabel lblInfantryDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartInfantryDoors = new JTextField(4);
    final JTextField tEndInfantryDoors = new JTextField(4);
    final JLabel lblInfantryUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartInfantryUnits = new JTextField(4);
    final JTextField tEndInfantryUnits = new JTextField(4);
    final JLabel lblSuperHeavyVehicleBays = new JLabel(Messages.getString(
          "MekSelectorDialog.Search.SuperHeavyVehicleBays"));
    final JTextField tStartSuperHeavyVehicleBays = new JTextField(4);
    final JTextField tEndSuperHeavyVehicleBays = new JTextField(4);
    final JLabel lblSuperHeavyVehicleDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartSuperHeavyVehicleDoors = new JTextField(4);
    final JTextField tEndSuperHeavyVehicleDoors = new JTextField(4);
    final JLabel lblSuperHeavyVehicleUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartSuperHeavyVehicleUnits = new JTextField(4);
    final JTextField tEndSuperHeavyVehicleUnits = new JTextField(4);
    final JLabel lblDropShuttleBays = new JLabel(Messages.getString("MekSelectorDialog.Search.DropshuttleBays"));
    final JTextField tStartDropShuttleBays = new JTextField(4);
    final JTextField tEndDropShuttleBays = new JTextField(4);
    final JLabel lblDropShuttleDoors = new JLabel(Messages.getString("MekSelectorDialog.Search.Doors"));
    final JTextField tStartDropShuttleDoors = new JTextField(4);
    final JTextField tEndDropShuttleDoors = new JTextField(4);
    final JLabel lblDropShuttleUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.Units"));
    final JTextField tStartDropShuttleUnits = new JTextField(4);
    final JTextField tEndDropShuttleUnits = new JTextField(4);
    final JLabel lblDockingCollars = new JLabel(Messages.getString("MekSelectorDialog.Search.DockingCollars"));
    final JTextField tStartDockingCollars = new JTextField(4);
    final JTextField tEndDockingCollars = new JTextField(4);
    final JLabel lblBattleArmorHandles = new JLabel(Messages.getString("MekSelectorDialog.Search.BattleArmorHandles"));
    final JTextField tStartBattleArmorHandles = new JTextField(4);
    final JTextField tEndBattleArmorHandles = new JTextField(4);
    final JLabel lblCargoBayUnits = new JLabel(Messages.getString("MekSelectorDialog.Search.CargoBayUnits"));
    final JTextField tStartCargoBayUnits = new JTextField(4);
    final JTextField tEndCargoBayUnits = new JTextField(4);
    final JLabel lblNavalRepairFacilities = new JLabel(Messages.getString(
          "MekSelectorDialog.Search.NavalRepairFacilities"));
    final JTextField tStartNavalRepairFacilities = new JTextField(4);
    final JTextField tEndNavalRepairFacilities = new JTextField(4);

    TransportsSearchTab() {
        btnTransportsClear.addActionListener(e -> clear());

        GridBagConstraints c = new GridBagConstraints();
        setLayout(new GridBagLayout());

        c.weighty = 0;
        c.anchor = GridBagConstraints.NORTHWEST;
        c.fill = GridBagConstraints.NONE;
        c.insets = new Insets(20, 10, 0, 0);

        c.gridwidth = 1;
        c.gridx = 0;
        c.gridy++;
        JPanel mbPanel = new JPanel();
        mbPanel.add(lblMekBays);
        mbPanel.add(tStartMekBays);
        mbPanel.add(new JLabel("-"));
        mbPanel.add(tEndMekBays);
        mbPanel.add(lblMekDoors);
        mbPanel.add(tStartMekDoors);
        mbPanel.add(new JLabel("-"));
        mbPanel.add(tEndMekDoors);
        mbPanel.add(lblMekUnits);
        mbPanel.add(tStartMekUnits);
        mbPanel.add(new JLabel("-"));
        mbPanel.add(tEndMekUnits);
        add(mbPanel, c);
        c.insets = new Insets(5, 10, 0, 0);
        c.gridx = 0;
        c.gridy++;
        JPanel abPanel = new JPanel();
        abPanel.add(lblASFBays);
        abPanel.add(tStartASFBays);
        abPanel.add(new JLabel("-"));
        abPanel.add(tEndASFBays);
        abPanel.add(lblASFDoors);
        abPanel.add(tStartASFDoors);
        abPanel.add(new JLabel("-"));
        abPanel.add(tEndASFDoors);
        abPanel.add(lblASFUnits);
        abPanel.add(tStartASFUnits);
        abPanel.add(new JLabel("-"));
        abPanel.add(tEndASFUnits);
        add(abPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel scbPanel = new JPanel();
        scbPanel.add(lblSmallCraftBays);
        scbPanel.add(tStartSmallCraftBays);
        scbPanel.add(new JLabel("-"));
        scbPanel.add(tEndSmallCraftBays);
        scbPanel.add(lblSmallCraftDoors);
        scbPanel.add(tStartSmallCraftDoors);
        scbPanel.add(new JLabel("-"));
        scbPanel.add(tEndSmallCraftDoors);
        scbPanel.add(lblSmallCraftUnits);
        scbPanel.add(tStartSmallCraftUnits);
        scbPanel.add(new JLabel("-"));
        scbPanel.add(tEndSmallCraftUnits);
        add(scbPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel dPanel = new JPanel();
        dPanel.add(lblDropShuttleBays);
        dPanel.add(tStartDropShuttleBays);
        dPanel.add(new JLabel("-"));
        dPanel.add(tEndDropShuttleBays);
        dPanel.add(lblDropShuttleDoors);
        dPanel.add(tStartDropShuttleDoors);
        dPanel.add(new JLabel("-"));
        dPanel.add(tEndDropShuttleDoors);
        dPanel.add(lblDropShuttleUnits);
        dPanel.add(tStartDropShuttleUnits);
        dPanel.add(new JLabel("-"));
        dPanel.add(tEndDropShuttleUnits);
        add(dPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel lvPanel = new JPanel();
        lvPanel.add(lblLightVehicleBays);
        lvPanel.add(tStartLightVehicleBays);
        lvPanel.add(new JLabel("-"));
        lvPanel.add(tEndLightVehicleBays);
        lvPanel.add(lblLightVehicleDoors);
        lvPanel.add(tStartLightVehicleDoors);
        lvPanel.add(new JLabel("-"));
        lvPanel.add(tEndLightVehicleDoors);
        lvPanel.add(lblLightVehicleUnits);
        lvPanel.add(tStartLightVehicleUnits);
        lvPanel.add(new JLabel("-"));
        lvPanel.add(tEndLightVehicleUnits);
        add(lvPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel hvPanel = new JPanel();
        hvPanel.add(lblHeavyVehicleBays);
        hvPanel.add(tStartHeavyVehicleBays);
        hvPanel.add(new JLabel("-"));
        hvPanel.add(tEndHeavyVehicleBays);
        hvPanel.add(lblHeavyVehicleDoors);
        hvPanel.add(tStartHeavyVehicleDoors);
        hvPanel.add(new JLabel("-"));
        hvPanel.add(tEndHeavyVehicleDoors);
        hvPanel.add(lblHeavyVehicleUnits);
        hvPanel.add(tStartHeavyVehicleUnits);
        hvPanel.add(new JLabel("-"));
        hvPanel.add(tEndHeavyVehicleUnits);
        add(hvPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel shvPanel = new JPanel();
        shvPanel.add(lblSuperHeavyVehicleBays);
        shvPanel.add(tStartSuperHeavyVehicleBays);
        shvPanel.add(new JLabel("-"));
        shvPanel.add(tEndSuperHeavyVehicleBays);
        shvPanel.add(lblSuperHeavyVehicleDoors);
        shvPanel.add(tStartSuperHeavyVehicleDoors);
        shvPanel.add(new JLabel("-"));
        shvPanel.add(tEndSuperHeavyVehicleDoors);
        shvPanel.add(lblSuperHeavyVehicleUnits);
        shvPanel.add(tStartSuperHeavyVehicleUnits);
        shvPanel.add(new JLabel("-"));
        shvPanel.add(tEndSuperHeavyVehicleUnits);
        add(shvPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel pmPanel = new JPanel();
        pmPanel.add(lblProtomekBays);
        pmPanel.add(tStartProtomekBays);
        pmPanel.add(new JLabel("-"));
        pmPanel.add(tEndProtomekBays);
        pmPanel.add(lblProtomekDoors);
        pmPanel.add(tStartProtomekDoors);
        pmPanel.add(new JLabel("-"));
        pmPanel.add(tEndProtomekDoors);
        pmPanel.add(lblProtomekUnits);
        pmPanel.add(tStartProtomekUnits);
        pmPanel.add(new JLabel("-"));
        pmPanel.add(tEndProtomekUnits);
        add(pmPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel baPanel = new JPanel();
        baPanel.add(lblBattleArmorBays);
        baPanel.add(tStartBattleArmorBays);
        baPanel.add(new JLabel("-"));
        baPanel.add(tEndBattleArmorBays);
        baPanel.add(lblBattleArmorDoors);
        baPanel.add(tStartBattleArmorDoors);
        baPanel.add(new JLabel("-"));
        baPanel.add(tEndBattleArmorDoors);
        baPanel.add(lblBattleArmorUnits);
        baPanel.add(tStartBattleArmorUnits);
        baPanel.add(new JLabel("-"));
        baPanel.add(tEndBattleArmorUnits);
        add(baPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel iPanel = new JPanel();
        iPanel.add(lblInfantryBays);
        iPanel.add(tStartInfantryBays);
        iPanel.add(new JLabel("-"));
        iPanel.add(tEndInfantryBays);
        iPanel.add(lblInfantryDoors);
        iPanel.add(tStartInfantryDoors);
        iPanel.add(new JLabel("-"));
        iPanel.add(tEndInfantryDoors);
        iPanel.add(lblInfantryUnits);
        iPanel.add(tStartInfantryUnits);
        iPanel.add(new JLabel("-"));
        iPanel.add(tEndInfantryUnits);
        add(iPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel dcPanel = new JPanel();
        dcPanel.add(lblDockingCollars);
        dcPanel.add(tStartDockingCollars);
        dcPanel.add(new JLabel("-"));
        dcPanel.add(tEndDockingCollars);
        add(dcPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel tsPanel = new JPanel();
        tsPanel.add(lblTroopSpace);
        tsPanel.add(tStartTroopSpace);
        tsPanel.add(new JLabel("-"));
        tsPanel.add(tEndTroopSpace);
        add(tsPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel cbPanel = new JPanel();
        cbPanel.add(lblCargoBayUnits);
        cbPanel.add(tStartCargoBayUnits);
        cbPanel.add(new JLabel("-"));
        cbPanel.add(tEndCargoBayUnits);
        add(cbPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel nrfPanel = new JPanel();
        nrfPanel.add(lblNavalRepairFacilities);
        nrfPanel.add(tStartNavalRepairFacilities);
        nrfPanel.add(new JLabel("-"));
        nrfPanel.add(tEndNavalRepairFacilities);
        add(nrfPanel, c);
        c.gridx = 0;
        c.gridy++;
        JPanel bahPanel = new JPanel();
        bahPanel.add(lblBattleArmorHandles);
        bahPanel.add(tStartBattleArmorHandles);
        bahPanel.add(new JLabel("-"));
        bahPanel.add(tEndBattleArmorHandles);
        add(bahPanel, c);

        c.weighty = 1;
        JPanel blankPanel = new JPanel();
        c.gridx = 0;
        c.gridy++;
        blankPanel.add(btnTransportsClear, c);
        add(blankPanel, c);
    }

    void clear() {
        tStartTroopSpace.setText("");
        tEndTroopSpace.setText("");
        tStartASFBays.setText("");
        tEndASFBays.setText("");
        tStartASFDoors.setText("");
        tEndASFDoors.setText("");
        tStartASFUnits.setText("");
        tEndASFUnits.setText("");
        tStartSmallCraftBays.setText("");
        tEndSmallCraftBays.setText("");
        tStartSmallCraftDoors.setText("");
        tEndSmallCraftDoors.setText("");
        tStartSmallCraftUnits.setText("");
        tEndSmallCraftUnits.setText("");
        tStartMekBays.setText("");
        tEndMekBays.setText("");
        tStartMekDoors.setText("");
        tEndMekDoors.setText("");
        tStartMekUnits.setText("");
        tEndMekUnits.setText("");
        tStartHeavyVehicleBays.setText("");
        tEndHeavyVehicleBays.setText("");
        tStartHeavyVehicleDoors.setText("");
        tEndHeavyVehicleDoors.setText("");
        tStartHeavyVehicleUnits.setText("");
        tEndHeavyVehicleUnits.setText("");
        tStartLightVehicleBays.setText("");
        tEndLightVehicleBays.setText("");
        tStartLightVehicleDoors.setText("");
        tEndLightVehicleDoors.setText("");
        tStartLightVehicleUnits.setText("");
        tEndLightVehicleUnits.setText("");
        tStartProtomekBays.setText("");
        tEndProtomekBays.setText("");
        tStartProtomekDoors.setText("");
        tEndProtomekDoors.setText("");
        tStartProtomekUnits.setText("");
        tEndProtomekUnits.setText("");
        tStartBattleArmorBays.setText("");
        tEndBattleArmorBays.setText("");
        tStartBattleArmorDoors.setText("");
        tEndBattleArmorDoors.setText("");
        tStartBattleArmorUnits.setText("");
        tEndBattleArmorUnits.setText("");
        tStartInfantryBays.setText("");
        tEndInfantryBays.setText("");
        tStartInfantryDoors.setText("");
        tEndInfantryDoors.setText("");
        tStartInfantryUnits.setText("");
        tEndInfantryUnits.setText("");
        tStartSuperHeavyVehicleBays.setText("");
        tEndSuperHeavyVehicleBays.setText("");
        tStartSuperHeavyVehicleDoors.setText("");
        tEndSuperHeavyVehicleDoors.setText("");
        tStartSuperHeavyVehicleUnits.setText("");
        tEndSuperHeavyVehicleUnits.setText("");
        tStartDropShuttleBays.setText("");
        tEndDropShuttleBays.setText("");
        tStartDropShuttleDoors.setText("");
        tEndDropShuttleDoors.setText("");
        tStartDropShuttleUnits.setText("");
        tEndDropShuttleUnits.setText("");
        tStartDockingCollars.setText("");
        tEndDockingCollars.setText("");
        tStartBattleArmorHandles.setText("");
        tEndBattleArmorHandles.setText("");
        tStartCargoBayUnits.setText("");
        tEndCargoBayUnits.setText("");
        tStartNavalRepairFacilities.setText("");
        tEndNavalRepairFacilities.setText("");
    }

    void applyState(AdvSearchState.TransportsState state) {
        tStartTroopSpace.setText(state.startTroopSpace);
        tEndTroopSpace.setText(state.endTroopSpace);
        tStartASFBays.setText(state.startASFBays);
        tEndASFBays.setText(state.endASFBays);
        tStartASFDoors.setText(state.startASFDoors);
        tEndASFDoors.setText(state.endASFDoors);
        tStartASFUnits.setText(state.startASFUnits);
        tEndASFUnits.setText(state.endASFUnits);
        tStartSmallCraftBays.setText(state.startSmallCraftBays);
        tEndSmallCraftBays.setText(state.endSmallCraftBays);
        tStartSmallCraftDoors.setText(state.startSmallCraftDoors);
        tEndSmallCraftDoors.setText(state.endSmallCraftDoors);
        tStartSmallCraftUnits.setText(state.startSmallCraftUnits);
        tEndSmallCraftUnits.setText(state.endSmallCraftUnits);
        tStartMekBays.setText(state.startMekBays);
        tEndMekBays.setText(state.endMekBays);
        tStartMekDoors.setText(state.startMekDoors);
        tEndMekDoors.setText(state.endMekDoors);
        tStartMekUnits.setText(state.startMekUnits);
        tEndMekUnits.setText(state.endMekUnits);
        tStartHeavyVehicleBays.setText(state.startHeavyVehicleBays);
        tEndHeavyVehicleBays.setText(state.endHeavyVehicleBays);
        tStartHeavyVehicleDoors.setText(state.startHeavyVehicleDoors);
        tEndHeavyVehicleDoors.setText(state.endHeavyVehicleDoors);
        tStartHeavyVehicleUnits.setText(state.startHeavyVehicleUnits);
        tEndHeavyVehicleUnits.setText(state.endHeavyVehicleUnits);
        tStartLightVehicleBays.setText(state.startLightVehicleBays);
        tEndLightVehicleBays.setText(state.endLightVehicleBays);
        tStartLightVehicleDoors.setText(state.startLightVehicleDoors);
        tEndLightVehicleDoors.setText(state.endLightVehicleDoors);
        tStartLightVehicleUnits.setText(state.startLightVehicleUnits);
        tEndLightVehicleUnits.setText(state.endLightVehicleUnits);
        tStartProtomekBays.setText(state.startProtomekBays);
        tEndProtomekBays.setText(state.endProtomekBays);
        tStartProtomekDoors.setText(state.startProtomekDoors);
        tEndProtomekDoors.setText(state.endProtomekDoors);
        tStartProtomekUnits.setText(state.startProtomekUnits);
        tEndProtomekUnits.setText(state.endProtomekUnits);
        tStartBattleArmorBays.setText(state.startBattleArmorBays);
        tEndBattleArmorBays.setText(state.endBattleArmorBays);
        tStartBattleArmorDoors.setText(state.startBattleArmorDoors);
        tEndBattleArmorDoors.setText(state.endBattleArmorDoors);
        tStartBattleArmorUnits.setText(state.startBattleArmorUnits);
        tEndBattleArmorUnits.setText(state.endBattleArmorUnits);
        tStartInfantryBays.setText(state.startInfantryBays);
        tEndInfantryBays.setText(state.endInfantryBays);
        tStartInfantryDoors.setText(state.startInfantryDoors);
        tEndInfantryDoors.setText(state.endInfantryDoors);
        tStartInfantryUnits.setText(state.startInfantryUnits);
        tEndInfantryUnits.setText(state.endInfantryUnits);
        tStartSuperHeavyVehicleBays.setText(state.startSuperHeavyVehicleBays);
        tEndSuperHeavyVehicleBays.setText(state.endSuperHeavyVehicleBays);
        tStartSuperHeavyVehicleDoors.setText(state.startSuperHeavyVehicleDoors);
        tEndSuperHeavyVehicleDoors.setText(state.endSuperHeavyVehicleDoors);
        tStartSuperHeavyVehicleUnits.setText(state.startSuperHeavyVehicleUnits);
        tEndSuperHeavyVehicleUnits.setText(state.endSuperHeavyVehicleUnits);
        tStartDropShuttleBays.setText(state.startDropShuttleBays);
        tEndDropShuttleBays.setText(state.endDropShuttleBays);
        tStartDropShuttleDoors.setText(state.startDropShuttleDoors);
        tEndDropShuttleDoors.setText(state.endDropShuttleDoors);
        tStartDropShuttleUnits.setText(state.startDropShuttleUnits);
        tEndDropShuttleUnits.setText(state.endDropShuttleUnits);
        tStartDockingCollars.setText(state.startDockingCollars);
        tEndDockingCollars.setText(state.endDockingCollars);
        tStartBattleArmorHandles.setText(state.startBattleArmorHandles);
        tEndBattleArmorHandles.setText(state.endBattleArmorHandles);
        tStartCargoBayUnits.setText(state.startCargoBayUnits);
        tEndCargoBayUnits.setText(state.endCargoBayUnits);
        tStartNavalRepairFacilities.setText(state.startNavalRepairFacilities);
        tEndNavalRepairFacilities.setText(state.endNavalRepairFacilities);
    }

    AdvSearchState.TransportsState getState() {
        var state = new AdvSearchState.TransportsState();
        state.startTroopSpace = tStartTroopSpace.getText();
        state.endTroopSpace = tEndTroopSpace.getText();
        state.startASFBays = tStartASFBays.getText();
        state.endASFBays = tEndASFBays.getText();
        state.startASFDoors = tStartASFDoors.getText();
        state.endASFDoors = tEndASFDoors.getText();
        state.startASFUnits = tStartASFUnits.getText();
        state.endASFUnits = tEndASFUnits.getText();
        state.startSmallCraftBays = tStartSmallCraftBays.getText();
        state.endSmallCraftBays = tEndSmallCraftBays.getText();
        state.startSmallCraftDoors = tStartSmallCraftDoors.getText();
        state.endSmallCraftDoors = tEndSmallCraftDoors.getText();
        state.startSmallCraftUnits = tStartSmallCraftUnits.getText();
        state.endSmallCraftUnits = tEndSmallCraftUnits.getText();
        state.startMekBays = tStartMekBays.getText();
        state.endMekBays = tEndMekBays.getText();
        state.startMekDoors = tStartMekDoors.getText();
        state.endMekDoors = tEndMekDoors.getText();
        state.startMekUnits = tStartMekUnits.getText();
        state.endMekUnits = tEndMekUnits.getText();
        state.startHeavyVehicleBays = tStartHeavyVehicleBays.getText();
        state.endHeavyVehicleBays = tEndHeavyVehicleBays.getText();
        state.startHeavyVehicleDoors = tStartHeavyVehicleDoors.getText();
        state.endHeavyVehicleDoors = tEndHeavyVehicleDoors.getText();
        state.startHeavyVehicleUnits = tStartHeavyVehicleUnits.getText();
        state.endHeavyVehicleUnits = tEndHeavyVehicleUnits.getText();
        state.startLightVehicleBays = tStartLightVehicleBays.getText();
        state.endLightVehicleBays = tEndLightVehicleBays.getText();
        state.startLightVehicleDoors = tStartLightVehicleDoors.getText();
        state.endLightVehicleDoors = tEndLightVehicleDoors.getText();
        state.startLightVehicleUnits = tStartLightVehicleUnits.getText();
        state.endLightVehicleUnits = tEndLightVehicleUnits.getText();
        state.startProtomekBays = tStartProtomekBays.getText();
        state.endProtomekBays = tEndProtomekBays.getText();
        state.startProtomekDoors = tStartProtomekDoors.getText();
        state.endProtomekDoors = tEndProtomekDoors.getText();
        state.startProtomekUnits = tStartProtomekUnits.getText();
        state.endProtomekUnits = tEndProtomekUnits.getText();
        state.startBattleArmorBays = tStartBattleArmorBays.getText();
        state.endBattleArmorBays = tEndBattleArmorBays.getText();
        state.startBattleArmorDoors = tStartBattleArmorDoors.getText();
        state.endBattleArmorDoors = tEndBattleArmorDoors.getText();
        state.startBattleArmorUnits = tStartBattleArmorUnits.getText();
        state.endBattleArmorUnits = tEndBattleArmorUnits.getText();
        state.startInfantryBays = tStartInfantryBays.getText();
        state.endInfantryBays = tEndInfantryBays.getText();
        state.startInfantryDoors = tStartInfantryDoors.getText();
        state.endInfantryDoors = tEndInfantryDoors.getText();
        state.startInfantryUnits = tStartInfantryUnits.getText();
        state.endInfantryUnits = tEndInfantryUnits.getText();
        state.startSuperHeavyVehicleBays = tStartSuperHeavyVehicleBays.getText();
        state.endSuperHeavyVehicleBays = tEndSuperHeavyVehicleBays.getText();
        state.startSuperHeavyVehicleDoors = tStartSuperHeavyVehicleDoors.getText();
        state.endSuperHeavyVehicleDoors = tEndSuperHeavyVehicleDoors.getText();
        state.startSuperHeavyVehicleUnits = tStartSuperHeavyVehicleUnits.getText();
        state.endSuperHeavyVehicleUnits = tEndSuperHeavyVehicleUnits.getText();
        state.startDropShuttleBays = tStartDropShuttleBays.getText();
        state.endDropShuttleBays = tEndDropShuttleBays.getText();
        state.startDropShuttleDoors = tStartDropShuttleDoors.getText();
        state.endDropShuttleDoors = tEndDropShuttleDoors.getText();
        state.startDropShuttleUnits = tStartDropShuttleUnits.getText();
        state.endDropShuttleUnits = tEndDropShuttleUnits.getText();
        state.startDockingCollars = tStartDockingCollars.getText();
        state.endDockingCollars = tEndDockingCollars.getText();
        state.startBattleArmorHandles = tStartBattleArmorHandles.getText();
        state.endBattleArmorHandles = tEndBattleArmorHandles.getText();
        state.startCargoBayUnits = tStartCargoBayUnits.getText();
        state.endCargoBayUnits = tEndCargoBayUnits.getText();
        state.startNavalRepairFacilities = tStartNavalRepairFacilities.getText();
        state.endNavalRepairFacilities = tEndNavalRepairFacilities.getText();
        return state;
    }
}
