/*
 * MegaMek - Copyright (C) 2004 Ben Mazur (bmazur@sev.org)
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the Free
 *  Software Foundation; either version 2 of the License, or (at your option)
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *  or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *  for more details.
 */

package megamek.common;

import java.io.Serializable;

import megamek.common.actions.AbstractAttackAction;

/**
 * Generated by a first pass through the physical attack actions
 */
public class PhysicalResult implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4011084578252131074L;
    public AbstractAttackAction aaa = null;
    public ToHitData toHit = null;
    public ToHitData toHitRight = null;
    public int roll = -1;
    public int rollRight = -1;
    public int damage = 0;
    public int damageRight = 0;
    public boolean pushBackResolved = false;
}