/*
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MegaMek.
 *
 * MegaMek is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MegaMek is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MegaMek was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package megamek.common.actions;

import java.io.Serial;

import megamek.client.ui.Messages;
import megamek.common.game.Game;
import megamek.common.units.Entity;

/**
 * Action for Standard (TO:AR) ghost target assignment during the pre-firing phase. A unit with qualifying equipment
 * (ECM, Angel ECM, 7+ ton Communications Equipment, or Cockpit Command Console) selects one friendly or one enemy unit
 * within range to apply ghost target effects to.
 *
 * <p>Per TO:AR rules, each piece of qualifying equipment on a unit can independently
 * generate one ghost target attempt per round.</p>
 */
public class GhostTargetAction extends AbstractEntityAction {

    @Serial
    private static final long serialVersionUID = 7461029384756102938L;

    /**
     * Sentinel equipment ID used when the ghost target is generated by a Cockpit Command Console (which is a cockpit
     * type on Meks, not a misc equipment item).
     */
    public static final int CCC_EQUIPMENT_ID = -2;

    private final int equipmentId;
    private final int targetEntityId;
    private final boolean targetIsFriendly;

    /**
     * Creates a new ghost target action.
     *
     * @param sourceEntityId   the ID of the entity generating the ghost target
     * @param equipmentId      the equipment number on the source entity (to support multiple qualifying equipment on
     *                         one unit)
     * @param targetEntityId   the ID of the entity being targeted
     * @param targetIsFriendly true if targeting a friendly unit (+1 to attacks against it), false if targeting an enemy
     *                         unit (+1 to attacks by it)
     */
    public GhostTargetAction(int sourceEntityId, int equipmentId, int targetEntityId,
          boolean targetIsFriendly) {
        super(sourceEntityId);
        this.equipmentId = equipmentId;
        this.targetEntityId = targetEntityId;
        this.targetIsFriendly = targetIsFriendly;
    }

    public int getEquipmentId() {
        return equipmentId;
    }

    public int getTargetEntityId() {
        return targetEntityId;
    }

    public boolean isTargetFriendly() {
        return targetIsFriendly;
    }

    @Override
    public String toSummaryString(final Game game) {
        Entity target = game.getEntity(targetEntityId);
        String targetName = (target != null) ? target.getShortName() : "?";
        if (targetIsFriendly) {
            return Messages.getString("GhostTargetAction.ProtectFriendly", targetName);
        } else {
            return Messages.getString("GhostTargetAction.JamEnemy", targetName);
        }
    }

    @Override
    public String toString() {
        return "[GhostTargetAction]: Unit ID " + getEntityId()
              + " equip " + equipmentId
              + (targetIsFriendly ? " protecting " : " jamming ")
              + "target " + targetEntityId;
    }
}
