#!/bin/python3

# Copyright (C) 2013-2025 The MegaMek Team. All Rights Reserved.
#
# This file is part of MegaMek.
#
# MegaMek is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MegaMek is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.


# Fix line endings. Run from project root.

import sys
import os
import os.path
import subprocess
import re

SVN_COMMAND = ['svn', 'propset', 'svn:eol-style']

DOS = '\r\n'
UNIX = '\n'

DOS_EXTENSIONS = ['.bat']
UNIX_EXTENSIONS = ['.properties', '.java', '.xml', '.txt', '.mms', '.board', '.tileset', '.mtf', '.blk']
EXCLUDE_DIRS = ['packaging_utils']

def convert(filepath, line_ending):
    file = open(filepath, 'rt')
    lines = file.readlines()
    file.close()
    file = open(filepath, 'wt', newline='\r\n')
    for line in lines:
        file.write(line)
    file.close()

def convert_files():
    for root, dirs, files in os.walk('.'):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        dos_files = []
        unix_files = []
        for filename in files:
            file_ext = os.path.splitext(filename)[1].lower()
            filepath = os.path.join(root, filename)
            if file_ext in UNIX_EXTENSIONS:
                print('UNIX: ', filepath)
                unix_files.append(filepath)
                convert(filepath, UNIX)
            elif file_ext in DOS_EXTENSIONS:
                print('DOS: ', os.path.join(root, filename))
                dos_files.append(filepath)
                convert(filepath, DOS)
        if len(dos_files) > 0:
            command = SVN_COMMAND + ['CRLF']
            command.extend(dos_files)
            subprocess.call(command)
        if len(unix_files) > 0:
            command = SVN_COMMAND + ['LF']
            command.extend(unix_files)
            subprocess.call(command)
    return 0

if __name__ == '__main__':
    sys.exit(convert_files())
