/*
 * MegaMek - Copyright (C) 2018 - The MegaMek Team
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 */
package megamek;

import java.io.File;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Includes utilities for backwards compatibility and, generally, stuff that
 * should be removed at some point in the future.
 */
public class LegacyMegamek {

    ////////////////////////////////////////////////////////////////////////////
    // When adding methods to this class, please make sure to
    // MENTION WHAT VERSION THE METHODS HAVE BEEN ADDED IN
    // and also describe what legacy behaviour you aim to support.
    //
    // Your code will be read in ten years by someone who's going to have no
    // idea what the old behaviour was and basically no means to find out.
    ////////////////////////////////////////////////////////////////////////////

    private static final Logger log = LogManager.getLogger(LegacyMegamek.class);

    private LegacyMegamek() {
        // no instances
    }

    /**
     * Looks at <tt>./logs</tt> and deletes all files matching the logs that
     * were generated by MM, MML and/or MHQ v0.45.1 (Sep 2018) or below.
     * <p/>
     * Old log files were named <tt>megameklog.txt</tt>,
     * <tt>megameklablog.txt</tt>, <tt>mekhqlog.txt</tt> or the same names with
     * a numeric suffix up to five (eg: <tt>megameklog.txt.3</tt> -  a log4j 1.2
     * rolling file appender was used).
     * <p/>
     * Old logs are being deleted for the sake of not confusing users who
     * upgrade from an old version (also, to avoid stale logs in bug reports),
     * so it is perfectly safe to remove this functionality once the community
     * has assimilated the log filename change.
     */
    public static void deleteLegacyLogFiles() {
        File logs = new File("./logs"); //$NON-NLS-1$
        File[] files = logs.listFiles();
        if (files != null) {
            for (File file : files) {
                String name = file.getName();
                boolean old = name.startsWith("megameklog.txt") //$NON-NLS-1$
                           || name.startsWith("mekhqlog.txt") //$NON-NLS-1$
                           || name.startsWith("megameklablog.txt"); //$NON-NLS-1$
                if (old) {
                    log.info("Deleting legacy log file {}", file.getPath()); //$NON-NLS-1$
                    try {
                        file.delete();
                    } catch (Throwable t) {
                        log.error("Could not delete legacy log file {}", file.getPath(), t); //$NON-NLS-1$
                    }
                }
            }
        }
    }

}
