package megamek.common.rules;
/*
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MegaMek.
 *
 * MegaMek is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MegaMek is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MegaMek was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */


import java.util.ArrayList;

import megamek.common.CriticalSlot;
import megamek.common.annotations.Nullable;

public abstract class RulesHeat {

    /**
     * Does standing generate heat.
     *
     * @return the heat generated by standing
     */
    public abstract int standingHeat();

    /**
     * Whether the optional Avoiding Shutdown rule (TO:AR p.102) is in play, which turns the roll to avoid a heat
     * shutdown into a Piloting Skill Roll. Both rulesets roll against the plain Avoid number by default; the rule is
     * a Tactical Operations option that either can use, and each implementation cites where its own default comes
     * from.
     *
     * @param avoidingShutdownOption the value of the Avoiding Shutdown game option
     *
     * @return {@code true} if shutdown avoidance uses the Avoiding Shutdown rule
     */
    public abstract boolean usesAvoidingShutdown(boolean avoidingShutdownOption);

    /**
     * How does heat affect when life support is hit.
     *
     * @param damageHeat the damage heat value
     * @param torsoMountedCockpit true if the cockpit is torso-mounted
     * @param mtHeat true if using MT heat rules
     * @param bPainShunt true if the pilot has a pain shunt
     * @return LifeSupportHeat This stores the heat level and damage amount
     */
    public abstract LifeSupportHeat checkLifeSupportHeat(int damageHeat,
                                        boolean torsoMountedCockpit,
                                        boolean mtHeat, boolean bPainShunt);

    /**
     * Which ammo goes boom.
     *
     * @param ammoCriticals the list of ammo critical slots
     * @return the ammo critical slot that explodes, or null if none
     */
    @Nullable
    public abstract CriticalSlot explodeAmmo(ArrayList<CriticalSlot> ammoCriticals);

    public record LifeSupportHeat(int heatLevel, int damageAmount) {}
}
